org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Can be music, tracker or lyrics
extType=music
extId=bilibili_audio
extClass=BilibiliExtension
extVersion=0.1.1
extVersionCode=2

extIconUrl=
extName=Bilibili Audio
extDescription=Search Bilibili videos and play their audio; open BV, av and au links.

extAuthor=weijianxian
extAuthorUrl=https://github.com/weijianxian

extRepoUrl=https://github.com/weijianxian/bilibili4echo
extUpdateUrl=https://api.github.com/repos/weijianxian/bilibili4echo/releases
